# Lab SQL

## Requirements

execute the following command to install the required packages:

```bash
pip install -r requirements.txt
```

In [17]:
"""Import csv files to sqlite3 database"""
import sqlite3
import pandas

conn = sqlite3.connect('courses.db')
# read csv files
courses = pandas.read_csv('Courses.csv', sep=',' , encoding='ISO-8859-1')
teachers = pandas.read_csv('Teachers.csv', sep=',' , encoding='ISO-8859-1')
students = pandas.read_csv('Students.csv', sep=',' , encoding='ISO-8859-1')
students_courses = pandas.read_csv('Students_Courses.csv', sep=',' , encoding='ISO-8859-1')
# create tables
courses.to_sql('TBL_COURSES', conn, index=False, if_exists='replace')
teachers.to_sql('TBL_TEACHERS', conn, index=False, if_exists='replace')
students.to_sql('TBL_STUDENTS', conn, index=False, if_exists='replace')
students_courses.to_sql('TBL_STUDENTS_COURSES', conn, index=False, if_exists='replace')
conn.close()

In [76]:
"""Queries"""

print('Cuántos cursos diferentes hay:')
conn = sqlite3.connect('courses.db')
cursor = conn.cursor()
cursor.execute('SELECT COUNT(DISTINCT Curso) AS COURSES FROM TBL_COURSES')
result = cursor.fetchall()
for row in result:
    print(row)

print('Cuántos alumnos hay en cada curso:')    
query = '''
SELECT c.CURSO, COUNT(DISTINCT SC.EstudianteID) AS STUDENTS 
FROM TBL_STUDENTS_COURSES as SC
INNER JOIN TBL_COURSES as C ON SC."Curso ID" = C."Curso ID"
GROUP BY C.CURSO
'''
cursor.execute(query)
result = cursor.fetchall()
for row in result:
    print(row)    
print('Determinar a partir de la respuesta anterior cuál es el curso más popular:')
query = '''
SELECT c.CURSO, COUNT(DISTINCT SC.EstudianteID) AS STUDENTS 
FROM TBL_STUDENTS_COURSES as SC
INNER JOIN TBL_COURSES as C ON SC."Curso ID" = C."Curso ID"
GROUP BY C.CURSO
HAVING STUDENTS = (
    SELECT MAX(STUDENTS) AS MAX_STUDENTS
    FROM (
        SELECT c.CURSO, COUNT(DISTINCT SC.EstudianteID) AS STUDENTS 
        FROM TBL_STUDENTS_COURSES as SC
        INNER JOIN TBL_COURSES as C ON SC."Curso ID" = C."Curso ID"
        GROUP BY C.CURSO
        )
    )
'''
print('De ese curso más popular extraer la lista de alumnos:')
query = '''
SELECT C.CURSO, S.Name AS STUDENT
FROM TBL_STUDENTS as S
INNER JOIN TBL_STUDENTS_COURSES as SC ON S.EstudianteID = SC.EstudianteID
INNER JOIN TBL_COURSES AS C ON SC."Curso ID" = C."Curso ID"
INNER JOIN (
    SELECT SC."Curso ID" AS Curso_ID, COUNT(DISTINCT SC.EstudianteID) AS STUDENTS 
    FROM TBL_STUDENTS_COURSES as SC
    GROUP BY SC."Curso ID"
    HAVING STUDENTS = (
        SELECT MAX(STUDENTS)
        FROM (
            SELECT c.CURSO, COUNT(DISTINCT SC.EstudianteID) AS STUDENTS 
            FROM TBL_STUDENTS_COURSES as SC
            INNER JOIN TBL_COURSES as C ON SC."Curso ID" = C."Curso ID"
            GROUP BY C.CURSO
            )
        )
    ) as C ON SC."Curso ID" = C.Curso_ID
'''
cursor.execute(query)
result = cursor.fetchall()
for row in result:
    print(row)

print('Definir en función del año de ingreso cuántos años hace que esta cada estudiante en la universidad:')
query = '''
SELECT S.Name as STUDENT, S.FechaIngreso, strftime('%Y', 'now') - substr(S.FechaIngreso, length(S.FechaIngreso) - 3, 4) AS YEARS  
FROM TBL_STUDENTS AS S
'''
cursor.execute(query)
result = cursor.fetchall()
for row in result:
    print(row)

conn.close()

Cuántos cursos diferentes hay:
(30,)
Cuántos alumnos hay en cada curso:
('Animacion Audiovisual', 31)
('Arbitro de futbol', 8)
('Audio for Games', 50)
('Coaching Ontologico', 8)
('Compliance y lavado de dinero', 20)
('Comunicación de Directivos', 5)
('Curso de Liquidacion de Sueldos', 6)
('Data Science', 1)
('Debates de politica exterior', 42)
('Deep Learning', 3)
('Derecho penal ', 43)
('Desarrollo con Angular', 30)
('Director Tecnico de Futbol', 3)
('Economia para principiantes', 17)
('Empleabilidad de personas con discapacidad', 43)
('Gestion del Inversor Financiero', 1)
('Gestion del transporte', 8)
('Introducción al Idioma Japonés Técnico y Manga', 7)
('Liderazgo Estrategico', 5)
('Luminotecnia', 3)
('Marketing Digital', 4)
('Nutricion deportiva', 46)
('PNL', 29)
('Periodismo deportivo', 2)
('Power BI', 2)
('Programacion Web Inicial', 43)
('Psicologia aplicada a las ciencias del deporte', 1)
('SQL', 46)
('Seguridad Electrica', 6)
('UX', 28)
Determinar a partir de la respuesta anterior cuál es el curso más popular:
De ese curso más popular extraer la lista de alumnos:
('Audio for Games', 'Veronica Ramirez')
('Audio for Games', 'Leonela Perez')
('Audio for Games', 'Sebastian Marich')
('Audio for Games', 'Amanda Amaya')
('Audio for Games', 'Lucia Amancio')
('Audio for Games', 'Lucia Lopez')
('Audio for Games', 'Florencia Winter')
('Audio for Games', 'Marina Iigo')
('Audio for Games', 'Santiago Lopez')
('Audio for Games', 'Silvina Diaz')
('Audio for Games', 'Melisa Peretti')
('Audio for Games', 'Pedro Gomez')
('Audio for Games', 'Anita Benitez')
('Audio for Games', 'Olivia Rodrigo')
('Audio for Games', 'Brian Perez')
('Audio for Games', 'Flavia Gomez')
('Audio for Games', 'Solana Hidalgo')
('Audio for Games', 'Lorena Marich')
('Audio for Games', 'Silvana Diaz')
('Audio for Games', 'Ernesto Diaz')
('Audio for Games', 'Maico Andrada')
('Audio for Games', 'Hector Cena')
('Audio for Games', 'Martin Dominguez')
('Audio for Games', 'Wanda Suarez')
('Audio for Games', 'Simon Aguirre')
('Audio for Games', 'Nicolas Sattler')
('Audio for Games', 'Facundo Priatti')
('Audio for Games', 'Berta Arce')
('Audio for Games', 'Juan Banegas')
('Audio for Games', 'Lisandro Martinez')
('Audio for Games', 'Karen Homs')
('Audio for Games', 'Alba Martinez')
('Audio for Games', 'Sofia Pratto')
('Audio for Games', 'Carla Irigo')
('Audio for Games', 'Soraya Guevara')
('Audio for Games', 'Juan Pablo Martinez')
('Audio for Games', 'Paloma Rojas')
('Audio for Games', 'Walter Benitez')
('Audio for Games', 'Mariana Trifone')
('Audio for Games', 'Jazmin Benitez')
('Audio for Games', 'Narela Pompei')
('Audio for Games', 'Maria Acosta')
('Audio for Games', 'Martina Gonzalez')
('Audio for Games', 'Evelyn Soria')
('Audio for Games', 'Marcelo Fernandez')
('Audio for Games', 'Daiana Loza')
('Audio for Games', 'Josefina Marco')
('Audio for Games', 'Lucas Lemos')
('Audio for Games', 'Stefania Roitman')
('Audio for Games', 'Ayelen Candia')
('Audio for Games', 'Miguel Diaz')
Definir en función del año de ingreso cuántos años hace que esta cada estudiante en la universidad:
('Veronica Ramirez', '11/21/2016', 8)
('Leonela Perez', '9/5/2015', 9)
('Sebastian Marich', '6/1/2016', 8)
('Amanda Amaya', '7/31/2015', 9)
('Lucia Amancio', '6/15/2015', 9)
('Lucia Lopez', '2/15/2017', 7)
('Lautaro Martinez', '1/1/2016', 8)
('Hector Peretti', '7/28/2015', 9)
('Horacio Rodriguez', '12/4/2016', 8)
('Lauriana Esposito', '5/17/2016', 8)
('Fabricio Arce', '7/17/2016', 8)
('Maria Zabala', '10/10/2015', 9)
('Romina Gusti', '4/3/2015', 9)
('Fernando Ulloa', '8/30/2016', 8)
('Walter Estevez', '5/12/2016', 8)
('Florencia Winter', '3/10/2016', 8)
('Marina Iigo', '9/23/2016', 8)
('Santiago Lopez', '9/15/2015', 9)
('Silvina Diaz', '1/6/2016', 8)
('Melisa Peretti', '11/2/2016', 8)
('Pedro Gomez', '2/3/2016', 8)
('Anita Benitez', '2/18/2017', 7)
('Roberto Cesar', '1/19/2016', 8)
('Exequiel Benegas', '8/4/2016', 8)
('Hector Lopez', '3/19/2015', 9)
('Ricardo Martinez', '12/23/2015', 9)
('Julian Alvarez', '12/28/2015', 9)
('Sol Allende', '4/2/2015', 9)
('Lisandro Gomez', '9/3/2016', 8)
('Pablo Tamiati', '4/11/2016', 8)
('Yanina Arce', '11/9/2016', 8)
('Yolanda Suarez', '8/21/2016', 8)
('Tiziano Kres', '8/10/2015', 9)
('Olivia Rodrigo', '7/27/2015', 9)
('Brian Perez', '7/11/2015', 9)
('Ignacio Peretti', '11/23/2015', 9)
('Susana Diaz', '3/6/2017', 7)
('Milagros Rodriguez', '10/31/2016', 8)
('Mariana Boero', '1/15/2016', 8)
('Aldana Suarez', '1/25/2017', 7)
('Federico Lucero', '8/4/2016', 8)
('Flavia Gomez', '2/13/2017', 7)
('Sofia Gomez', '3/10/2017', 7)
('Solana Hidalgo', '8/22/2016', 8)
('Lorena Marich', '5/28/2015', 9)
('Silvana Diaz', '2/22/2016', 8)
('Walter Perez', '12/26/2016', 8)
('Ernesto Diaz', '1/6/2016', 8)
('Maico Andrada', '1/5/2016', 8)
('Prisila Ballester', '3/24/2016', 8)
('Romina Ulloa', '7/13/2016', 8)
('Carmen Cena', '1/25/2016', 8)
('Hector Cena', '4/26/2015', 9)
('Martin Dominguez', '11/7/2016', 8)
('Wanda Suarez', '5/19/2016', 8)
('Simon Aguirre', '9/18/2015', 9)
('Nicolas Sattler', '2/19/2017', 7)
('Facundo Priatti', '2/13/2017', 7)
('Juan Lopez', '7/23/2015', 9)
('Florencia Pereyra', '6/10/2015', 9)
('Evelyn Alvarez', '2/17/2016', 8)
('Rodrigo Foco', '12/4/2016', 8)
('Fiorella Perez', '4/27/2015', 9)
('Tatiana Gomez', '8/31/2015', 9)
('Raul Diaz', '12/21/2015', 9)
('Ricardo Montaner', '7/1/2015', 9)
('German Arroyo', '1/5/2017', 7)
('Agustin Martinez', '1/15/2016', 8)
('Ignacio Montagnini', '1/9/2016', 8)
('Berta Arce', '2/26/2017', 7)
('Juan Banegas', '3/30/2015', 9)
('Gonzalo Villegas', '12/7/2015', 9)
('Lisandro Martinez', '10/14/2016', 8)
('Camilo Pereira', '12/13/2016', 8)
('Karen Homs', '2/9/2016', 8)
('Franco Piatti', '4/1/2016', 8)
('Lucia Fassano', '8/26/2016', 8)
('Nahuel Sanchez', '10/11/2016', 8)
('Alba Martinez', '10/27/2015', 9)
('Lucia Guevara', '5/10/2015', 9)
('Nahuel Guevara', '5/25/2016', 8)
('Sofia Pratto', '11/18/2015', 9)
('Carla Irigo', '2/27/2017', 7)
('Soraya Guevara', '6/6/2015', 9)
('Juan Pablo Martinez', '6/28/2015', 9)
('Paloma Rojas', '3/13/2016', 8)
('Juan Molina', '9/15/2016', 8)
('Mauricio Rivarola', '3/8/2016', 8)
('Julieta Morales', '4/2/2015', 9)
('Federico Valis', '5/5/2016', 8)
('Lucas Olmos', '12/18/2016', 8)
('Walter Olmos', '8/16/2015', 9)
('Belen Lucio', '7/16/2015', 9)
('Fatima Santos', '5/7/2015', 9)
('Guada Santillan', '1/16/2016', 8)
('Debora Paez', '2/25/2016', 8)
('Julieta Tavechio', '10/11/2016', 8)
('Agustin Gomez', '3/22/2015', 9)
('Agostina Mari', '3/30/2015', 9)
('Constanza Amoroso', '12/12/2016', 8)
('Ayelen Martinez', '6/10/2016', 8)
('Luisina Peretti', '7/15/2016', 8)
('Antonella Rocho', '4/11/2016', 8)
('Celeste Justina', '10/25/2016', 8)
('Leonela Rodriguez', '12/27/2016', 8)
('Franco Rodriguez', '3/12/2016', 8)
('Betiana Ferreyra', '1/18/2017', 7)
('Stefania Arce', '12/26/2016', 8)
('Ivan Paez', '8/30/2015', 9)
('Ezequiel Berra', '9/11/2016', 8)
('Renata Paez', '4/21/2015', 9)
('Ignacio Gonzalez', '2/8/2016', 8)
('Victoria Estevez', '4/30/2016', 8)
('Franco Peyrone', '12/7/2016', 8)
('Pablo Castillo', '11/15/2015', 9)
('Camilo Ferreyra', '11/7/2016', 8)
('Jorge Chacon', '2/20/2017', 7)
('Matiaz Sunca', '7/27/2016', 8)
('Maria Mejia', '7/25/2016', 8)
('Camila Suarez', '4/1/2016', 8)
('Fernando Palacios', '9/24/2015', 9)
('Micaela Vazquez', '3/14/2015', 9)
('Leo Lia', '1/14/2016', 8)
('Walter Benitez', '10/1/2015', 9)
('Mariana Trifone', '5/7/2016', 8)
('Jazmin Benitez', '3/16/2015', 9)
('Narela Pompei', '11/21/2015', 9)
('Maria Acosta', '10/3/2015', 9)
('Martina Gonzalez', '6/15/2015', 9)
('Evelyn Soria', '4/9/2015', 9)
('Marcelo Fernandez', '12/8/2016', 8)
('Daiana Loza', '1/12/2016', 8)
('Josefina Marco', '3/16/2016', 8)
('Lucas Lemos', '11/13/2016', 8)
('Eliana Gallero', '11/16/2016', 8)
('Stefania Roitman', '12/27/2016', 8)
('Ayelen Candia', '5/1/2015', 9)
('Miguel Diaz', '8/2/2016', 8)
('Antonella Rocuso', '12/16/2015', 9)
('Carolina Martini', '4/23/2016', 8)
('Solana Franco', '6/2/2015', 9)
('Jimena Montes', '7/27/2016', 8)
('Ana Leyria', '8/30/2016', 8)